myProject/MyProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #  honey pot admin page
    path('admin/', include('admin_honeypot.urls')),
    # actual admin page
    path('blobbyAdmin/', admin.site.urls),
    # apps
    path('', include('frontapp.urls')),
    # path('', include('otherapp.urls'))
   

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
         path("__debug__/", include(debug_toolbar.urls))
    ] +urlpatterns

myProject/frontapp/urls.py
from django.urls import path
from . import views

app_name = 'frontapp'
# separate url linked to core project url for when multiple apps in project
# urlconf
urlpatterns = [

    path('', views.HomeView.as_view(), name="Home"),
    
    path('Services/', views.ServicesView.as_view(), name="Services"),
    path('Gallery/', views.Gallery.as_view(), name="Gallery"),
    path('News/', views.News.as_view(), name="News"),
    path('Success/', views.SuccessView.as_view(), name="Success"),
    path('Error404/', views.Error404View.as_view(), name="Error404"),
    path('includes/contactForm/', views.processContactFormView, name="ContactForm"),
    path('includes/footer/', views.FooterListView.as_view(), name="FooterData"), 
    path('includes/commentsForm/<uuid:id>', views.CommentOnPostView.as_view(), name="CommentOnPost"),
    path('News/<uuid:id>', views.News.as_view(), name="LikePost"),
    
    
]   

myProject/frontapp/forms.py
from django.forms import ModelForm, Textarea
from .models import Comment, GeneralEnquiry, Post


class ContactForm(ModelForm):
    class Meta:
        model = GeneralEnquiry
        fields = ["name", "email", "phone_number", "subject", "enquiry", "last_name"]
        widgets = {"enquiry": Textarea(attrs={"cols": 60, "rows": 5}), }

form = ContactForm()


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [ "name","body"]
        widgets = {"body": Textarea(attrs={"cols": 50, "rows": 5}), }
        
form = CommentForm()

class LikeForm(ModelForm):
    class Meta:
        model = Post 
        fields = ["likes"]
form = LikeForm() 

myProject/frontapp/views.py
import requests
from django.shortcuts import get_object_or_404, render, redirect
from .models import NavHTMLPage,EditableStaticContent,PreviousExamplesImages,Faqs,Vehicle, Comment, Images, Post, Testimonials, BusinessDetails
from django.contrib import messages
from .forms import ContactForm, CommentForm
from django.views.generic import ListView,View
from datetime import datetime

def get_object_or_custom_404(model,id):
    try:
        return model.objects.get(id=id)
    except model.DoesNotExist:
        return redirect("frontapp:Error404")
  
# class based views to replace function based  
class HomeView(ListView):
    model = Testimonials
    context_object_name = "testimonial"
    template_name = "Home.html"
    
    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        try:
            context['testimonial'] = Testimonials.objects.all()[:3]
        except Testimonials.DoesNotExist:
            context['testimonial'] = None
        context['editableStaticContent'] = EditableStaticContent.objects.all()
        context['navHTMLPage'] = NavHTMLPage.objects.all()
        
        return context


class Gallery(ListView):
    model = Images   
    context_object_name = "context"
    template_name = "Gallery.html"
    
    def get_context_data(self, **kwargs):
        context = super(Gallery, self).get_context_data(**kwargs)
        context['vehicle_images'] = Images.objects.all()
        context['vehicle'] = Vehicle.objects.all()
        context['peImages'] = PreviousExamplesImages.objects.all()
        context['editableStaticContent'] = EditableStaticContent.objects.all()
        
        return context


    
class News(ListView):
    model = Comment
    template_name = "News.html"
    context_object_name = "context"
    
    def get_context_data(self, **kwargs):
        context = super(News, self).get_context_data(**kwargs)     
        context['post'] = Post.objects.all()
        context['testimonial'] = Testimonials.objects.all()[3:]
        context['editableStaticContent'] = EditableStaticContent.objects.all()
        context['comment_form'] = CommentForm()
        return context
    
    def post(self,request,id): 
        post_obj = get_object_or_custom_404(Post,id=id)
     
        if str(id) in request.session.get('liked_posts', []):
            warning_message = f"You have already liked the {post_obj.title} post."
            messages.warning(request, warning_message)
            return redirect('/News/#'+str(id),{'post_obj': post_obj})
        post_obj.likes += 1
        # Assign current post to comment
        try:
            # Save comment to db
            post_obj.save()
            request.session.setdefault('liked_posts', []).append(str(id))
            request.session.modified = True
            success_message = f"A like was given to the post {post_obj.title}."
            messages.success(request, success_message)
            return redirect('/News/#'+str(id),{'post_obj': post_obj})
        except Exception as e:
            messages.error(request, "Apologies but an error occurred liking the post. Please try again.") 
            messages.error(request, str(e))
        
        context = {'post_obj': post_obj}
        return redirect('/News/#'+str(id) , context )   
        
    
class FooterListView(ListView):
    model = BusinessDetails
    template_name = "includes/footer.html"
    context_object_name = "context"
    
    def get_context_data(self, **kwargs):
        context = super(FooterListView, self).get_context_data(**kwargs)
        context['data'] = BusinessDetails.objects.all()
        return context

class ServicesView(ListView):
    model = Faqs
    template_name = "Services.html"
    context_object_name = "context"
    
    def get_context_data(self,**kwargs):
        context = super(ServicesView, self).get_context_data(**kwargs)
        context['faqs'] = Faqs.objects.all()
        context['editableStaticContent'] = EditableStaticContent.objects.all()
              
        return context
    
class SuccessView(View):
    def get(self,request):
        return render(request, "Success.html")

class Error404View(View):
    def get(self,request):
        return render(request, "Error404.html")
    
#django central
class CommentOnPostView(ListView):
    
    def get(self, request,id):
        post_obj = get_object_or_custom_404(Post,id=id)
        comment_form = CommentForm()
        context = {'comment_form':comment_form,'post_obj':post_obj}
        return render(request, 'includes/commentsForm.html', context)
    
    def post(self,request,id):
        post_obj = get_object_or_custom_404(Post,id=id)
        new_comment = None   
        comment_form = CommentForm(data=request.POST)
        
        if comment_form.is_valid():
            # Create Comment object, don't save to db
            new_comment = comment_form.save(commit=False)
            # Assign current post to comment
            new_comment.post = post_obj
            try:
                # Save comment to db
                new_comment.save()
                success_message = f"A new comment was successfully submitted for post {post_obj.title} and awaiting moderation."
                messages.success(request, success_message)
                return redirect('/News/#'+str(id))
            except Exception as e:
                messages.error(request, "Apologies but an error occurred submitting your comment. Please try again.") 
                messages.error(request, str(e))
        
        # if not valid return to form      
        comment_form = CommentForm()
        context = {'post_obj': post_obj,'new_comment': new_comment,'comment_form': comment_form}
        
        return redirect('/News/#'+str(id) , context )   
    
    
# function based views ########

# pass in form and clean data 
def validate_contact_form(form):
    name = form.cleaned_data["name"]
    subject = form.cleaned_data["subject"]
    email = form.cleaned_data["email"]
    phone_number = form.cleaned_data["phone_number"]
    message = form.cleaned_data["enquiry"]
    last_name = form.cleaned_data["last_name"]
    #honeypot check for bots, hidden from user in html page
    if last_name is not None:
        return False
    else:
        return name, subject, email, phone_number, message, last_name
    
# pass in cleaned form data and send in an email
def send_email(name, subject, email, phone_number, message, last_name):
    url = "https://formspree.io/f/mbjvoewj"
    payload = {
        "name": name,
        "subject": subject,
        "email": email,
        "phone_number": phone_number,
        "message": message,
        "last_name":last_name
    }
    try:
        response = requests.post(url, data=payload)
        print("Send mail response: ", response)
        response.raise_for_status()
        status_code = response.status_code
    except requests.RequestException as e:
            print("An error occurred within the send_email() function. Error: ", e)
            messages.error(
                'Error code: ',e)
    
    return status_code
    
# process contact form and return result
def processContactFormView(request):
    if request.method == "GET":
        form = ContactForm()
    elif request.method == "POST":
        form = ContactForm(request.POST or None)
        
        if form.is_valid():
            date = datetime.now()
            #return boolean
            clean_form = validate_contact_form(form)
            if clean_form is not False:
                name, subject, email, phone_number, message, last_name = clean_form
                status_code = send_email(name, subject, email, phone_number, message, last_name)
                if status_code == 200:
                    clean_form.save()
                    messages.success(
                        request, 'A new enquiry was successfully added to the db')
                    return redirect("frontapp:Success")
                elif status_code == 404:
                    messages.error(
                        request, 'Error 404 has occurred during contactFormView() on  ',date)
                    return redirect("frontapp:Error404")
                else:
                    messages.error(
                        request, 'Sorry, something went wrong sending the email, try again. Status code: ',status_code)
                    return
            else:
                
                messages.error(request, 'The form is invalid and may contain data in the last_name field which is not visible to the user and indicates a Bot has filled it in. This form will not be processed.',date)
        else:
            form = ContactForm()
    context = {'form': form}
    return render(request, 'ContactForm.html', context)            

myProject/frontapp/templates/Base.html
<!DOCTYPE html>
<html lang="en">
  {% load crispy_forms_tags %}{% load static %}

  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Meta data for site -->
    <title>
      {% block title %}USAVehicleImports - Importer Specialist of Pre-owned
      Modern or Classic American Vehicles and Bikes{% endblock title %}
    </title>
    <meta name="author" content="USA Vehicle Imports" />
    <meta
      name="description"
      content="Personalised importer of pre-owned american vehicles and bikes from the east coast to the UK. 
        Provides sourcing, purchasing and transportation services as a full or individual package 
        including a door-to-door service, covid safe if required."
    />

    <!-- Favicon icon -->
    <link href="{% static "/images/other/favicon.ico" %}" rel="icon"
    type="image/x-icon" />

    <!-- font awesome -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"
    />

    <!-- Links for bootstrap css (js at bottom of page)-->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />

    <!-- css styles -->
    <link rel="stylesheet" type="text/css" href="{% static "/css/style.css" %}">
  </head>

  <body>
    {% include 'includes/nav.html' %}

    <section>{% block content %} {% endblock content %}</section>

    <!--prettier-ignore-->
    {% include 'includes/contactForm.html' %}
    
    {% include 'includes/footer.html' %}

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
      crossorigin="anonymous"
    ></script>
    <script src="{% static '/js/script.js' %}"></script>
  </body>
</html>

myProject/frontapp/templates/Error404.html
<!-- prettier-ignore -->
{% extends "Base.html" %}{% block title %}Error 404 Page{% endblock title %}
{% block content %}{% load static %}
<div class="container">
  <a href="/" class="fa fa-arrow-circle-o-left fa-2 text-decoration-none pt-2"
    >Back home</a
  >
  <div class="container-fluid">
    <div class="flex-lg-row mx-auto" style="max-width: 380px">
      <img
        class="card-img-top p-1 rounded-4"
        src="{% static 'images/other/oops.jpg' %}"
      />

      <div class="card-body text-center p-2">
        <h2 class="card-title">Sorry, an error 404 has occurred</h2>
        <p class="card-text text-black-50">
          This error has appeared when trying to load some data from the
          database.
          <br />
          Try again, we hope it works but if not then we apologise and will try
          to fix it lickety-split.
        </p>
      </div>
      <div class="card-img-bottom mb-0">
        <img
          class="img-fluid"
          src="{% static 'images/other/thank-you.jpg' %}"
        />
      </div>
    </div>
  </div>
</div>

{% endblock %}

myProject/frontapp/templates/Gallery.html
<!-- prettier-ignore -->
{% extends "Base.html" %}{% block title %}Gallery Page{% endblock title %}
  {% block content %} {% load static %}

<!-- move dynamic invent cards script to views and just call -->
<div class="image-parallax fade-in">
  <div class="container">
    <div class="header-content">
      <!--prettier-ignore-->
      {% for content in editableStaticContent %} 
      {% if content.title == 'GalleryHero' %}
      <h1 class="mt-5 mb-4">{{ content.header }}</h1>
      {% for para in content.escToPara_fk.all %}
      <p>{{ para.paragraph }}</p>
      {% endfor %}{% endif %}{% endfor %}
    </div>
  </div>
</div>

<!-- Dynamically created inventory cards from db -->
{% include 'includes/inventoryCarousel.html' %}

<!-- Text to redirect to social media -->
<div class="container-fluid bg-black m-0 p-5 text-white-50">
  <!--prettier-ignore-->
  {% for content in editableStaticContent %} 
  {% if content.title == 'GalleryBreaker' %}
  <h1>{{ content.header }}</h1>
  {% for para in content.escToPara_fk.all %}
  <p>{{ para.paragraph }}</p>
  {% endfor %}{% endif %}{% endfor %}
</div>

<!-- Introduction text to fixed gallery of previous stock examples -->
<div class="image-parallax-other">
  <div class="container">
    <div class="header-content">
      <!--prettier-ignore-->
      {% for content in editableStaticContent %} 
      {% if content.title == 'GalleryExamplePics' %}
      <h1 class="mt-5 mb-4">{{ content.header }}</h1>
      {% for para in content.escToPara_fk.all %}
      <p>{{ para.paragraph }}</p>
      {% endfor %}{% endif %}{% endfor %}
    </div>
  </div>
</div>

<!-- Fixed gallery carousel of cars non-dynamic-->
<div class="container-fluid mb-5 mt-5">
  <div class="container rounded-3">
    {% include 'includes/previousExamplesCarousel.html' %}
  </div>
</div>

{% endblock %}

myProject/frontapp/templates/Home.html
<!--prettier-ignore-->
{% extends "Base.html" %}{% block content %} {% load static %} 
{% for content in editableStaticContent %}
<header>
  {% if content.title == 'HomeHero' %}
  <div class="header-parallax fade-in">
    <div class="container">
      <div id="HomeHero" class="header-content">
        {% for para in content.escToPara_fk.all %}
        <h1>{{ content.header }}</h1>
        <p>{{ para.paragraph }}</p>
        {% endfor %}
      </div>
    </div>
  </div>
  {% endif %}
</header>
<section>
  {% if content.title == 'Home' %}
  <div class="container-fluid bg-light text-center">
    <div
      id="Home"
      class="col-md-8 p-3 bg-dark-subtle shadow position-relative top-0 start-50 translate-middle rounded-2"
    >
      <h2>{{ content.header }}</h2>
    </div>

    <div class="container-fluid px-lg-5">
      <div class="row row-cols-1 row-cols-sm-2 pb-lg-5">
        <!-- fudging bootstrap5 to contain text within a pill shape as the element does not change for text-wrap to give required effect -->
        <div
          class="col-sm-9 pt-5 pb-5 px-4 mb-4 bg-danger-subtler rounded-pill px-xxl-5"
        >
          <div class="text-center rounded-5 px-2 pt-3 pt-md-5 px-md-5 pt-xl-2">
            <div class="text pt-5 px-3 px-sm-3 px-lg-5">
              <!--prettier-ignore-->
              <h5>{{ content.subHeader }}</h5>
              {% for para in content.escToPara_fk.all %}
              <p>{{ para.paragraph }}</p>
              {% endfor %}
            </div>
          </div>
          <br />
          <div class="container-fluid position-relative">
            {% for image in content.escToImage_fk.all %}
            <img
              class="img-fluid mt-2 rounded-2 shadow"
              src="{{ image.images.url }}"
              alt="USA Vehicle Imports logo image"
            />

            <button
              type="button"
              class="btn btn-sm position-absolute top-100 start-0 translate-middle rounded-circle"
              data-bs-toggle="collapse"
              data-bs-target="#imageData"
              aria-expanded="false"
              aria-controls="imageData"
            >
              <i class="fa fa-info" aria-hidden="true"></i>
            </button>
            <div class="collapse" id="imageData">
              <div class="card card-body bg-danger-subtler">
                {{ image.description }}
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
        <!-- Links to main pages of interest -->
        <div class="col-12 col-sm-3 px-xl-5">
          <div class="row row-cols-3 row-cols-sm-1 pt-sm-5">
            <!--prettier-ignore-->
            {% for page in navHTMLPage %} 
            {% if page.page == 'Services' %}
            <div class="col-4 my-2 home-card link-effect px-5 px-sm-2 pt-sm-3">
              <div class="img-fluid mx-4 mx-sm-0">
                {% with pagetitle=page.page %}
                <a
                  class="nav-item nav-link"
                  href="{% url 'frontapp:'|add:pagetitle %}"
                  >{{ page.title }}<img
                    class="img-thumbnail mt-1 rounded-lg hover-effect"
                    src="{{ page.imageIcon.url}}" /></a
                >{% endwith %}
              </div>
              <div class="nav-link-info">
                <p>{{ page.description }}</p>
              </div>
            </div>
            <!--prettier-ignore-->
            {% endif %}{% endfor %}
            {% for page in navHTMLPage %}
            {% if page.page == 'Gallery' %}
            <div class="col-4 my-2 home-card link-effect px-5 px-sm-2 pt-sm-3">
              <div class="img-fluid mx-4 mx-sm-0">
                {% with pagetitle=page.page %}
                <a
                  class="nav-item nav-link"
                  href="{% url 'frontapp:'|add:pagetitle %}"
                  >{{ page.title }}<img
                    class="img-thumbnail mt-1 rounded-pill hover-effect"
                    src="{{ page.imageIcon.url}}" /></a
                >{% endwith %}
              </div>
              <div class="nav-link-info">
                <p>{{ page.description }}</p>
              </div>
            </div>
            <!--prettier-ignore-->
            {% endif %}{% endfor %} {% for page in navHTMLPage %} 
            {% if page.page == 'News' %}

            <div class="col-4 my-2 home-card link-effect px-5 px-sm-2 pt-sm-3">
              <div class="img-fluid mx-4 mx-sm-0">
                {% with pagetitle=page.page %}
                <a
                  class="nav-item nav-link"
                  href="{% url 'frontapp:'|add:pagetitle %}"
                  >{{ page.title }}<img
                    class="img-thumbnail mt-1 rounded-circle hover-effect"
                    src="{{ page.imageIcon.url}}" /></a
                >{% endwith %}
              </div>
              <div class="nav-link-info">
                <p>{{ page.description }}</p>
              </div>
            </div>
            {% endif %}{% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endif %}
</section>
{% endfor %} {% if testimonial %}
<section>{% include 'includes/testimonial.html' %}</section>
{% endif %} {% endblock content %}

myProject/frontapp/templates/HomeCopy.html
{% extends "Base.html" %}{% block content %} {% load static %}
<header>
  <div class="header-parallax fade-in">
    <div class="container">
      <div class="header-content">
        <h1>WELCOME to USA Vehicle Imports</h1>
        <p>
          We specialise in wholesale and import of pre-owned vehicles from East
          Coast USA.
        </p>
      </div>
    </div>
  </div>
</header>
<section>
  <div class="container-fluid bg-light text-center">
    <div
      class="col-md-8 p-3 bg-dark-subtle shadow position-relative top-0 start-50 translate-middle rounded-2"
    >
      <h2>
        American Car Sales, Imports, Transportation, Registration, and Sourcing
      </h2>
    </div>
    <div class="container-fluid px-lg-5">
      <div class="row row-cols-1 row-cols-sm-2 pb-lg-5">
        <!-- fudging bootstrap5 to contain text within a pill shape as the element does not change for text-wrap to give required effect -->
        <div
          class="col-sm-9 pt-5 pb-5 px-4 mb-4 bg-danger-subtler rounded-pill px-xxl-5"
        >
          <div class="text-center rounded-5 px-2 pt-3 pt-md-5 px-md-5 pt-xl-2">
            <p class="pt-4 px-5">
              We provide a safe and secure way to import cars directly from the
              USA.
            </p>
            <p>We can select and buy cars on your behalf and request.</p>
            <p>
              All vehicles are personally inspected by our team before purchase
              in the United States.
            </p>
            <p>
              We deliver your vehicle(s) from door to door using our own
              transport team.
            </p>
            <p>
              We have over 25 years experience in buying used American cars,
              RVs, convertibles, classics, motorbikes, and much more!
            </p>
            <p>
              Delivery can be as soon as 4 weeks depending on shipping
              locations.
            </p>
          </div>
          <br />
          <div class="container-fluid position-relative">
            <img
              class="img-fluid mt-2 rounded-2 shadow"
              src="{% static '/images/home/banner-4.jpg' %}"
              alt="USA Vehicle Imports logo image"
            />
            <button
              type="button"
              class="btn btn-sm position-absolute top-100 start-0 translate-middle rounded-circle"
              data-bs-toggle="collapse"
              data-bs-target="#imageData"
              aria-expanded="false"
              aria-controls="imageData"
            >
              <i class="fa fa-info" aria-hidden="true"></i>
            </button>
            <div class="collapse" id="imageData">
              <div class="card card-body bg-danger-subtler">
                1966 Plymouth Fury 3 v8
              </div>
            </div>
          </div>
        </div>
        <!-- Links to main pages of interest -->
        <div class="col-12 col-sm-3 px-xl-5">
          <div class="row row-cols-3 row-cols-sm-1">
            <div class="col-4 my-2 home-card link-effect">
              <div class="img-fluid">
                <a
                  class="nav-item nav-link"
                  href="{% url 'frontapp:Services' %}"
                  >Services<img class="img-thumbnail mt-1 rounded-lg
                  hover-effect" src="{% static "images/home/Services.jpg" %}"
                  /></a
                >
              </div>
              <div class="nav-link-info">
                <p>We source, import, and deliver the vehicle you want</p>
              </div>
            </div>
            <div class="col-4 my-2 home-card link-effect">
              <div class="img-fluid">
                <a class="nav-item nav-link" href="{% url 'frontapp:Gallery' %}"
                  >Gallery<img class="img-thumbnail mt-1 rounded-pill
                  hover-effect" src="{% static "images/home/Gallery.jpg" %}"
                  /></a
                >
              </div>
              <div class="nav-link-info">
                <p>Examples of current and previous stock</p>
              </div>
            </div>

            <div class="col-4 my-2 home-card link-effect">
              <div class="img-fluid">
                <a class="nav-item nav-link" href="{% url 'frontapp:News' %}"
                  >News<img class="img-thumbnail mt-1 rounded-circle
                  hover-effect" src="{% static "images/home/News.jpg" %}" /></a
                >
              </div>
              <div class="nav-link-info">
                <p>What we have been up to</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section>{% include 'includes/testimonial.html' %}</section>

{% endblock content %}

myProject/frontapp/templates/Success.html
<!-- prettier-ignore -->
{% extends "Base.html" %}{% block title %}Email Success Page{% endblock title %}
  {% block content %}{% load static %}

<div class="container">
  <a href="/" class="fa fa-arrow-circle-o-left fa-2 text-decoration-none pt-2"
    >Back home</a
  >
  <div class="container-fluid">
    <div class="flex-lg-row mx-auto" style="max-width: 280px">
      <img
        class="card-img-top p-3"
        src="{% static 'images/other/background-envelope.jpg' %}"
      />

      <div class="card-body text-center">
        <h2 class="card-title">Email sent successfully</h2>
        <p class="card-text text-black-50">
          Many thanks for your email we will get back to you as soon as
          possible.
        </p>
      </div>
      <div class="card-img-bottom mb-0">
        <img
          class="img-fluid"
          src="{% static 'images/other/thank-you.jpg' %}"
        />
      </div>
    </div>
  </div>
</div>
{% endblock %}