myProject/MyProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #  honey pot admin page
    path('admin/', include('admin_honeypot.urls')),
    # actual admin page
    path('blobbyAdmin/', admin.site.urls),
    # apps
    path('', include('frontapp.urls')),
    # path('', include('otherapp.urls'))
   

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
         path("__debug__/", include(debug_toolbar.urls))
    ] +urlpatterns

myProject/frontapp/urls.py
from django.urls import path
from . import views

app_name = 'frontapp'
# separate url linked to core project url for when multiple apps in project
# urlconf
urlpatterns = [

    path('', views.HomeView.as_view(), name="Home"),
    
    path('Services/', views.ServicesView.as_view(), name="Services"),
    path('Gallery/', views.Gallery.as_view(), name="Gallery"),
    path('News/', views.News.as_view(), name="News"),
    path('Success/', views.SuccessView.as_view(), name="Success"),
    path('Error404/', views.Error404View.as_view(), name="Error404"),
    path('includes/contactForm/', views.processContactFormView, name="ContactForm"),
    path('includes/footer/', views.FooterListView.as_view(), name="FooterData"), 
    path('includes/commentsForm/<uuid:id>', views.CommentOnPostView.as_view(), name="CommentOnPost"),
    path('News/<uuid:id>', views.News.as_view(), name="LikePost"),
    
    
]   

myProject/frontapp/forms.py
from django.forms import ModelForm, Textarea
from .models import Comment, GeneralEnquiry, Post


class ContactForm(ModelForm):
    class Meta:
        model = GeneralEnquiry
        fields = ["name", "email", "phone_number", "subject", "enquiry", "last_name"]
        widgets = {"enquiry": Textarea(attrs={"cols": 60, "rows": 5}), }

form = ContactForm()


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [ "name","body"]
        widgets = {"body": Textarea(attrs={"cols": 50, "rows": 5}), }
        
form = CommentForm()

class LikeForm(ModelForm):
    class Meta:
        model = Post 
        fields = ["likes"]
form = LikeForm() 

myProject/frontapp/views.py
import requests
from django.shortcuts import get_object_or_404, render, redirect
from .models import NavHTMLPage,EditableStaticContent,PreviousExamplesImages,Faqs,Vehicle, Comment, Images, Post, Testimonials, BusinessDetails
from django.contrib import messages
from .forms import ContactForm, CommentForm
from django.views.generic import ListView,View
from datetime import datetime

def get_object_or_custom_404(model,id):
    try:
        return model.objects.get(id=id)
    except model.DoesNotExist:
        return redirect("frontapp:Error404")
  
# class based views to replace function based  
class HomeView(ListView):
    model = Testimonials
    context_object_name = "testimonial"
    template_name = "Home.html"
    
    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        try:
            context['testimonial'] = Testimonials.objects.all()[:3]
        except Testimonials.DoesNotExist:
            context['testimonial'] = None
        context['editableStaticContent'] = EditableStaticContent.objects.all()
        context['navHTMLPage'] = NavHTMLPage.objects.all()
        
        return context


class Gallery(ListView):
    model = Images   
    context_object_name = "context"
    template_name = "Gallery.html"
    
    def get_context_data(self, **kwargs):
        context = super(Gallery, self).get_context_data(**kwargs)
        context['vehicle_images'] = Images.objects.all()
        context['vehicle'] = Vehicle.objects.all()
        context['peImages'] = PreviousExamplesImages.objects.all()
        context['editableStaticContent'] = EditableStaticContent.objects.all()
        
        return context


    
class News(ListView):
    model = Comment
    template_name = "News.html"
    context_object_name = "context"
    
    def get_context_data(self, **kwargs):
        context = super(News, self).get_context_data(**kwargs)     
        context['post'] = Post.objects.all()
        context['testimonial'] = Testimonials.objects.all()[3:]
        context['editableStaticContent'] = EditableStaticContent.objects.all()
        context['comment_form'] = CommentForm()
        return context
    
    def post(self,request,id): 
        post_obj = get_object_or_custom_404(Post,id=id)
     
        if str(id) in request.session.get('liked_posts', []):
            warning_message = f"You have already liked the {post_obj.title} post."
            messages.warning(request, warning_message)
            return redirect('/News/#'+str(id),{'post_obj': post_obj})
        post_obj.likes += 1
        # Assign current post to comment
        try:
            # Save comment to db
            post_obj.save()
            request.session.setdefault('liked_posts', []).append(str(id))
            request.session.modified = True
            success_message = f"A like was given to the post {post_obj.title}."
            messages.success(request, success_message)
            return redirect('/News/#'+str(id),{'post_obj': post_obj})
        except Exception as e:
            messages.error(request, "Apologies but an error occurred liking the post. Please try again.") 
            messages.error(request, str(e))
        
        context = {'post_obj': post_obj}
        return redirect('/News/#'+str(id) , context )   
        
    
class FooterListView(ListView):
    model = BusinessDetails
    template_name = "includes/footer.html"
    context_object_name = "context"
    
    def get_context_data(self, **kwargs):
        context = super(FooterListView, self).get_context_data(**kwargs)
        context['data'] = BusinessDetails.objects.all()
        return context

class ServicesView(ListView):
    model = Faqs
    template_name = "Services.html"
    context_object_name = "context"
    
    def get_context_data(self,**kwargs):
        context = super(ServicesView, self).get_context_data(**kwargs)
        context['faqs'] = Faqs.objects.all()
        context['editableStaticContent'] = EditableStaticContent.objects.all()
              
        return context
    
class SuccessView(View):
    def get(self,request):
        return render(request, "Success.html")

class Error404View(View):
    def get(self,request):
        return render(request, "Error404.html")
    
#django central
class CommentOnPostView(ListView):
    
    def get(self, request,id):
        post_obj = get_object_or_custom_404(Post,id=id)
        comment_form = CommentForm()
        context = {'comment_form':comment_form,'post_obj':post_obj}
        return render(request, 'includes/commentsForm.html', context)
    
    def post(self,request,id):
        post_obj = get_object_or_custom_404(Post,id=id)
        new_comment = None   
        comment_form = CommentForm(data=request.POST)
        
        if comment_form.is_valid():
            # Create Comment object, don't save to db
            new_comment = comment_form.save(commit=False)
            # Assign current post to comment
            new_comment.post = post_obj
            try:
                # Save comment to db
                new_comment.save()
                success_message = f"A new comment was successfully submitted for post {post_obj.title} and awaiting moderation."
                messages.success(request, success_message)
                return redirect('/News/#'+str(id))
            except Exception as e:
                messages.error(request, "Apologies but an error occurred submitting your comment. Please try again.") 
                messages.error(request, str(e))
        
        # if not valid return to form      
        comment_form = CommentForm()
        context = {'post_obj': post_obj,'new_comment': new_comment,'comment_form': comment_form}
        
        return redirect('/News/#'+str(id) , context )   
    
    
# function based views ########

# pass in form and clean data 
def validate_contact_form(form):
    name = form.cleaned_data["name"]
    subject = form.cleaned_data["subject"]
    email = form.cleaned_data["email"]
    phone_number = form.cleaned_data["phone_number"]
    message = form.cleaned_data["enquiry"]
    last_name = form.cleaned_data["last_name"]
    #honeypot check for bots, hidden from user in html page
    if last_name is not None:
        return False
    else:
        return name, subject, email, phone_number, message, last_name
    
# pass in cleaned form data and send in an email
def send_email(name, subject, email, phone_number, message, last_name):
    url = "https://formspree.io/f/mbjvoewj"
    payload = {
        "name": name,
        "subject": subject,
        "email": email,
        "phone_number": phone_number,
        "message": message,
        "last_name":last_name
    }
    try:
        response = requests.post(url, data=payload)
        print("Send mail response: ", response)
        response.raise_for_status()
        status_code = response.status_code
    except requests.RequestException as e:
            print("An error occurred within the send_email() function. Error: ", e)
            messages.error(
                'Error code: ',e)
    
    return status_code
    
# process contact form and return result
def processContactFormView(request):
    if request.method == "GET":
        form = ContactForm()
    elif request.method == "POST":
        form = ContactForm(request.POST or None)
        
        if form.is_valid():
            date = datetime.now()
            #return boolean
            clean_form = validate_contact_form(form)
            if clean_form is not False:
                name, subject, email, phone_number, message, last_name = clean_form
                status_code = send_email(name, subject, email, phone_number, message, last_name)
                if status_code == 200:
                    clean_form.save()
                    messages.success(
                        request, 'A new enquiry was successfully added to the db')
                    return redirect("frontapp:Success")
                elif status_code == 404:
                    messages.error(
                        request, 'Error 404 has occurred during contactFormView() on  ',date)
                    return redirect("frontapp:Error404")
                else:
                    messages.error(
                        request, 'Sorry, something went wrong sending the email, try again. Status code: ',status_code)
                    return
            else:
                
                messages.error(request, 'The form is invalid and may contain data in the last_name field which is not visible to the user and indicates a Bot has filled it in. This form will not be processed.',date)
        else:
            form = ContactForm()
    context = {'form': form}
    return render(request, 'ContactForm.html', context)            

myProject/frontapp/templates/includes/commentsForm.html
<!--included in news.html-->
{% load crispy_forms_tags %}

<div
  class="modal fade"
  id="createCommentsForm-{{ post.id }}"
  tabindex="-1"
  aria-labelledby="createCommentsFormLabel-{{ post.id }}"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header text-bg-success">
        <h5 class="modal-title" id="createCommentsFormLabel-{{ post.id }}">
          Leave a comment
        </h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body">
        <form
          id="commtForm"
          method="POST"
          style="margin-top: 1.3em"
          action="{%  url 'frontapp:CommentOnPost' post.id %}"
        >
          {% csrf_token %} {{ comment_form|crispy }}
          <div class="modal-footer">
            <button
              type="button"
              class="btn btn-secondary"
              data-bs-dismiss="modal"
            >
              Close
            </button>
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </form>
        <p class="bg-info-subtle p-2">
          Note: Once submitted your comment will await moderation by the admin
          team (not a robot!) before appearing. This is just a general
          precautionary step and we appreciate your understanding. From all the
          team here, we would like to thank you for taking the time to let us
          know what you think.
        </p>
      </div>
    </div>
  </div>
</div>

myProject/frontapp/templates/includes/contactForm.html
<!--included in News.html-->
{% load crispy_forms_tags %}
<div class="container-fluid container-form-bgcolor pt-3 pb-3" id="enqForm">
  <div class="row mt-5 mb-5">
    <div class="col-12 mt-2 mb-2">
      <button
        type="button"
        class="btn btn-secondary btn-lg d-block w-50 m-auto shadow rounded-pill"
        data-bs-toggle="collapse"
        data-bs-target="#collapseContactForm"
        aria-expanded="false"
        aria-controls="collapseContactForm"
      >
        Get in touch
      </button>
    </div>
  </div>
  <a id="createEnquiry"></a>
  <!-- Hidden collapsable enquiry form using third party email service FormSpree.io. 
      Receiving email account logged with formspree.-->
  <div class="collapse" id="collapseContactForm">
    <form id="conForm" method="POST" action="{% url 'frontapp:ContactForm' %}">
      <div
        class="container bg-light px-1 pt-3 pb-3 p-sm-3 mb-5 shadow rounded-3"
        style="max-width: 600px"
      >
        <h1 class="text-center text-black-50">Enquiry form</h1>
        <!-- name, email, phone number, enquiry comments -->
        <!--prettier-ignore-->
        {% csrf_token %} 
        {{ form.name|as_crispy_field }}
        {{ form.email|as_crispy_field }}
        {{ form.phone_number|as_crispy_field }}
        {{ form.subject|as_crispy_field }}
        {{ form.enquiry|as_crispy_field }}
        {{ form.last_name.as_hidden }}
        <button type="submit" class="btn btn-primary mx-3">Submit</button>
      </div>
    </form>
  </div>
</div>

myProject/frontapp/templates/includes/faqs.html
<div class="accordion accordion-flush" id="accordionFlushExample">
  {% for faqs in faqs %}
  <div class="accordion-item">
    <h2 class="accordion-header" id="flush-heading{{faqs.id}}">
      <button
        class="accordion-button collapsed"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#flush-collapse{{faqs.id}}"
        aria-expanded="false"
        aria-controls="flush-collapse{{faqs.id}}"
      >
        {{ faqs.question }}
      </button>
    </h2>
    <div
      id="flush-collapse{{faqs.id}}"
      class="accordion-collapse collapse"
      aria-labelledby="flush-heading{{faqs.id}}"
      data-bs-parent="#accordionFlushExample"
    >
      <div class="accordion-body text-bg-primary">{{ faqs.answer }}</div>
    </div>
  </div>
  {% endfor %}
</div>

myProject/frontapp/templates/includes/footer.html
 <!--included in base.html-->
 {% load static %}
 

 <a id="contactUs"></a>
<footer class="bg-dark text-white">
    <div class="container p-5">
        <div class="row row-cols-1 row-cols-sm-2 justify-content-center">
            <div class="col" >
                
                <p class="fs-3">Get in touch:</p>
                <p>Enquiry form above</a></p>
                
                {% for data in data %}
                {% if data %}
                {% if data.contact_phone %}
                <p> Phone: {{ data.contact_phone }} </p>
                {% endif %}  
                
                {% if data.contact_mobile %}
                <p>Mobile: {{ data.contact_mobile }}</p>
                {% endif %}
                
                <p>Email<a href="mailto:{{ data.contact_email }}"> usavehicleimports</a></p> 
                {% endif %} 
                                
                <p>
                    {% if data.facebook %}
                    <a class="nav-item nav-link" 
                     title="Facebook" target="_blank" href="{{ data.facebook }}">Facebook <i class="fa fa-facebook-square mx-1" style="color: coral"></i
                        ></a> 
                        {% endif %}   {% if data.instagram %}                   
                    <a class="nav-item nav-link" title="Instagram" target="_blank" href="{{ data.instagram }}">or Instagram <i class="fa fa-instagram mx-1" style="color: coral"></i
                        ></a>
                        {% endif %}{% if data.twitter %}
                    <a class="nav-item nav-link" title="Twitter" target="_blank" href="{{ data.twitter }}">or Twitter <i class="fa fa-twitter-square mx-1" style="color: coral"></i
                        ></a>
                        {% endif %}{% if data.linkedIn %}
                    <a class="nav-item nav-link" title="LinkedIn" target="_blank" href="{{ data.linkedIn }}">or LikedIn <i class="fa fa-linkedin-square mx-1" style="color: coral"></i
                        ></a>
                        {% endif %}
                </p>   
                         
            </div>
          
            <div class="col lh-1">
                
                {% if data %}
                <p class="m-1 lh-sm">{{ data.business_name }}</p>
                <p class="m-1 lh-sm">
                    {{ data.address_1stline }},
                    {{ data.address_2ndline }},
                    {{ data.address_town }}
                    {{ data.address_county }}
                </p>
                {% if data.contact_name %}
                <p class="m-1 lh-sm">Contact: {{ data.contact_name }}</p> 
                {% endif %}  
                <!-- google maps link -->
                
                <p class="m-1 lh-sm">
                    <a href="{{ data.google_map_link }}"
                    target="_blank">
                        {{ data.address_postcode }}
                    </a>
                </p>
                {% endif %}
                
                <a class="navbar-brand" href="#">
                    <img class="img-thumbnail mt-3 mb-3 w-50" src="{{ data.business_logo.url }}" alt="USA Vehicle Imports logo">
                </a>
                <div class="text-sm-start lh-sm text-white-50">
                    <p class="m-0 p-0 fw-light" style="font-size: 0.8rem;">
                        {% now "Y" as curr_yr %}
                        Copyright @{{ curr_yr }}
                        <span class="text-uppercase">{{ data.business_name }}</span></p>
                    <p class="fw-lighter" style="font-size: 0.7rem;">All rights reserved</p>
                </div>
                {% endfor %}
                <a href="{% url 'admin:index' %}" class="position-relative bottom-0 start-100 text-white" style="font-size: 0.7rem;">Admin</a>
            </div>
            
        </div>
    </div>

</footer>

myProject/frontapp/templates/includes/inventoryCarousel.html
{% load static %}

<div class="container-fluid bg-light-subtle mb-5 mt-3" method="GET">
  <div class="container p-4">
    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4 g-3">
      {% for item in vehicle %}
      <div class="col">
        <!-- Vehicle Card with Carousel -->
        <div class="card shadow h-100 rounded-2 rounded-border-bottom">
          <!-- Carousel -->
          <div
            id="carousel-{{ item.id }}"
            class="carousel slide"
            data-bs-interval="false"
          >
            <!-- Bootstrap Carousel Indicators -->
            <ol class="carousel-indicators">
              {% for image in item.vehicle_fk.all %}
              <a
                data-bs-target="#carousel-{{ item.id }}"
                data-bs-slide-to="{{ forloop.counter0 }}"
                class="{% if forloop.first %}active{% endif %}"
                aria-current="{% if forloop.first %}true{% else %}false{% endif %}"
                aria-label="Slide {{ forloop.counter }}"
              ></a>
              {% endfor %}
            </ol>

            <!-- Carousel Slides -->
            <div class="carousel-inner">
              {% for image in item.vehicle_fk.all %}
              <div
                class="carousel-item {% if forloop.first %}active{% endif %}"
              >
                <img
                  src="{{ image.images.url }}"
                  class="d-block w-100"
                  alt="Vehicle Image"
                />
              </div>
              {% endfor %}
            </div>

            <!-- Carousel Controls -->
            <a
              class="carousel-control-prev"
              href="#carousel-{{ item.id }}"
              role="button"
              data-bs-slide="prev"
            >
              <span
                class="carousel-control-prev-icon"
                aria-hidden="true"
              ></span>
              <span class="visually-hidden">Previous</span>
            </a>
            <a
              class="carousel-control-next"
              href="#carousel-{{ item.id }}"
              role="button"
              data-bs-slide="next"
            >
              <span
                class="carousel-control-next-icon"
                aria-hidden="true"
              ></span>
              <span class="visually-hidden">Next</span>
            </a>
          </div>
          <!-- /Carousel -->

          <!-- Card Body -->
          <div class="card-body d-flex flex-column">
            <h5 class="card-title">{{ item.name }}</h5>
            <hr />
            <p class="card-text">Price: ${{ item.price }}</p>
            <p class="card-text">Availability: {{ item.availability }}</p>
            <p class="card-text">Description: {{ item.description }}</p>
            <hr />

            <button
              class="btn btn-outline-primary align-self-end mt-auto"
              data-bs-toggle="modal"
              data-bs-target="#createEnquiryForm-{{ item.pk }}"
              aria-expanded="false"
              aria-controls="createEnquiryForm"
            >
              Make an enquiry
            </button>

            {% include 'includes/inventoryEnquiryForm.html' %}
          </div>
        </div>
        <!-- /Vehicle Card with Carousel -->
      </div>
      {% endfor %}
    </div>
  </div>
</div>

myProject/frontapp/templates/includes/inventoryEnquiryForm.html
<!--included in inventoryCarousel.html-->
{% load crispy_forms_tags %}

<!-- enquiry modal -->
<div
  class="modal fade"
  id="createEnquiryForm-{{ item.pk }}"
  tabindex="-1"
  aria-labelledby="createEnquiryFormLabel-{{ item.pk }}"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="createEnquiryFormLabel-{{ item.pk }}">
          Enquiry Form
        </h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body">
        <form method="POST" action="{% url 'frontapp:ContactForm' %}">
          {% csrf_token %}
          <!--prettier-ignore-->
          {{ form.name|as_crispy_field }}
          {{ form.email|as_crispy_field }}
          {{ form.phone_number|as_crispy_field }}
          <!-- first car name in all enquiry submissions -->

          <div class="form-group">
            <label for="{{ form.subject.id_for_label }}">Subject:</label>
            <input
              type="text"
              name="subject"
              value="{{ item.name }}"
              class="form-control"
              id="{{ form.name.id_for_label }}"
            />
          </div>
          <div class="form-group">
            <label for="{{ form.enquiry.id_for_label }}">Enquiry:</label>
            <textarea
              name="enquiry"
              rows="5"
              class="form-control"
              id="{{ form.enquiry.id_for_label }}"
            >
I would like to enquire about the {{ item.name }} that is shown on your website. Please contact me on the phone number or email provided. Many thanks.</textarea
            >
          </div>
          <div class="modal-footer">
            <button
              type="button"
              class="btn btn-secondary"
              data-bs-dismiss="modal"
            >
              Close
            </button>
            <button class="btn btn-primary">Submit</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<!--end modal form -->

myProject/frontapp/templates/includes/messages.html
{% if messages %} {% for message in messages %}
<div class="position-fixed bottom-0 end-0 p-3" style="z-index: 11">
  <div
    id="showToast"
    class="toast {{message.tags}}"
    role="alert"
    aria-live="assertive"
    aria-atomic="true"
  >
    <div class="toast-header">
      <i class="fa fa-comments"> </i>
      <strong class="me-auto"> Message</strong>
      <small class="text-muted">form submission</small>
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="toast"
        aria-label="Close"
      ></button>
    </div>
    <div class="toast-body">{{ message|safe }}</div>
  </div>
</div>
<!--end message toast-->
{% endfor %} {% endif %}

myProject/frontapp/templates/includes/postCard.html
<!--included in News.html-->
<!-- mt-4 mb-auto alows collapse action downwards -->
<!-- change to mb-4 my-auto for upwards show action, interesting! -->
{% for post in post %}
<div class="col mt-4 mb-auto">
  <!--for redirect on form submit-->
  <a id="{{ post.id }}"></a>
  <!--building a card-->
  <div class="card h-100 box-shadow-dark mx-auto" style="max-width: 450px">
    <!-- header -->
    <div class="card-header bg-primary text-white rounded-0">
      <h2 class="card-title">{{ post.title }}</h2>
      <p class="card-text">Author: {{ post.author }}</p>
      <p class="card-text">Date: {{ post.created }}</p>
    </div>
    <!-- dealing with images -->
    {% if post.image_upload %}
    <div class="card-img">
      <img
        src="{{ post.image_upload.url }}"
        class="card-img shadow-sm img-fit rounded-0"
        alt="Sorry uploaded image not working"
      />
    </div>
    {% endif %} {% if post.body_taster %}
    <div class="card-body bg-light">
      <h5 class="card-subtitle">{{ post.body_taster }}...</h5>
    </div>
    {% endif %}
    <!--start content to collapse/hide-->
    <div class="collapse" id="contents-{{ post.pk }}">
      <!-- main body text -->
      <div class="card-body">
        <p class="card-text">{{ post.body }}</p>
      </div>
      {% if post.image_url %}
      <div class="card-img-bottom">
        <img
          src="{{ post.image_url }}"
          class="card-img img-fit mb-3"
          alt="Sorry url image link not working"
        />
      </div>
      {% endif %} {% if post.video %}
      <div class="card-body mt-auto">
        <video class="w-100 shadow-sm" controls>
          <source
            src="{{ MEDIA_URL }}{{ post.video.url }}"
            type="video/mp4"
            alt="Sorry video cannot be displayed"
          />
          Your browser does not support the video tag.
        </video>
      </div>
      {% endif %}
      <hr />
      <!-- display only administrators activated comments as moderated-->
      <h4 class="text-left px-2"><em>Moderated Comments</em></h4>
      {% for comment in post.comments.all %} {% if comment.active == True %}
      <hr />

      <div class="comments p-1">
        <p class="font-weight-bold mb-0">
          {{ comment.name }}
          <span class="text-muted font-weight-normal">
            {{ comment.created_on }}
          </span>
        </p>
        <p><q>{{ comment.body }}</q></p>
        {% if comment.reply %}
        <p class="px-3 text-black-50">
          <em><u>Reply:</u><q>{{ comment.reply }}</q></em>
        </p>
        {% endif %}
      </div>

      {% endif %} {% endfor %}
    </div>
    <!--end content-->

    <div class="card-footer bg-light mt-auto">
      <!-- Reveal more to read -->
      <p>
        <button
          class="btn btn-outline-info"
          data-bs-toggle="collapse"
          data-bs-target="#contents-{{ post.id }}"
          aria-expanded="false"
          aria-controls="contents-{{ post.id }}"
          ar
        >
          Read More
        </button>
      </p>
      <!--Social media - like,comment,copy link options as buttons-->
      <hr />

      <div class="row row-sm-col-2">
        <div class="col d-flex justify-content-center">
          <!-- like option -->
          <form
            method="POST"
            action="{% url 'frontapp:LikePost' post.id %}"
            input="hidden"
          >
            {% csrf_token %}
            <button
              type="submit"
              name="post_id"
              value="{{ post.id }} "
              class="btn p-1 hover-effect"
              data-bs-toggle="tooltip"
              data-bs-placement="bottom"
              title="Like"
            >
              <i class="fa fa-gratipay"></i>
              <span class="badge bg-info">{{ post.likes }}</span> Likes
            </button>
          </form>
        </div>

        <div class="col d-flex justify-content-center">
          <!--comment option-->

          <button
            class="btn m-0 p-1 hover-effect"
            title="Leave a comment"
            data-bs-toggle="modal"
            data-bs-target="#createCommentsForm-{{ post.id }}"
            aria-expanded="false"
            aria-controls="createCommentsForm"
            data-bs-toggle="tooltip"
            data-bs-placement="bottom"
          >
            <!--prettier-ignore-->
            <i class="fa fa-comment-o"></i>
            <span class="badge bg-info">{{ post.comment_count_true }}</span>
            Comments
          </button>

          {% include 'includes/commentsForm.html' %}
        </div>
      </div>
      <div class="row">
        <!--prettier-ignore-->
      </div>
      <div class="row">
        <span
          ><a
            class="btn btn-sm btn-primary my-1"
            href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fusavehicleimports.com&quote=USA%20Vehicle%20Imports"
            target="_blank"
            title="Share on Facebook"
          >
            <i class="fa fa-facebook-square"></i>
            Share
          </a>
          <a
            class="btn btn-sm btn-info my-1"
            href="https://twitter.com/intent/tweet?source=http%3A%2F%2Fusavehicleimports.com&text=USA%20Vehicle%20Imports:%20http%3A%2F%2Fusavehicleimports.com"
            target="_blank"
            title="Tweet"
          >
            <i class="fa fa-twitter-square"></i>
            Tweet
          </a>
          <a
            class="btn btn-sm btn-danger my-1"
            href="http://pinterest.com/pin/create/button/?url=http%3A%2F%2Fusavehicleimports.com&description=Sales%2C%20Sourcing%2C%20Importing%20of%20American%20Cars%20and%20Bikes"
            target="_blank"
            title="Pin it"
          >
            <i class="fa fa-pinterest-square"></i>
            Pin it
          </a>
        </span>
      </div>
    </div>
  </div>
  <!--end card build-->
</div>
{% endfor %}
<!--end all cards-->